version: 0.2.0-{build}-{branch}

pull_requests:
  do_not_increment_build_number: true

image:
  - Visual Studio 2017
  - Ubuntu1804

environment:
  ACCESS_TOKEN:
    secure: 5eRS/D19C7CpbD+vIetjgnH/gIgFXnXcTofCMO/aODo=
  NCRYPTF_TEST_API:
    secure: 4vpB/+IPUL0gtP71pQN95reJCgkaxQ6nj1JGDqVYosg=

configuration:
  - Release

matrix:
  fast_finish: true

dotnet_csproj:
  patch: true
  file: '**\*.csproj'
  version: '{version}'
  package_version: '{version}'
  assembly_version: '{version}'
  file_version: '{version}'
  informational_version: '{version}'

nuget:
  disable_publish_on_pr: true

before_build:
- cmd: >-
    dotnet --version

    dotnet restore --verbosity m

build:
  publish_nuget: true
  publish_nuget_symbols: true
  include_nuget_references: true
  parallel: true
  verbosity: normal

after_build:
  - cmd: dotnet publish ./ncryptf/ncryptf.csproj -c Release

test:
  assemblies:
    only:
      - ncryptf.Test

artifacts:
  - path: bin/Release/netstandard2.0/publish